---
abstract: 'ETL with a Shell'
author:
  - 'Doug Bell <preaction@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Dir::Self: '0'
  JSON::PP: '0'
  Module::Build: '0.28'
  Test::Compile: '0'
  Test::Deep: '0'
  Test::Differences: '0'
  Test::Exception: '0'
  Test::Lib: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ETL-Yertl
recommends:
  JSON::PP: '0'
  JSON::XS: '0'
  Text::CSV: '0'
  Text::CSV_XS: '0'
  YAML::Syck: '0'
  YAML::XS: '0'
requires:
  Data::Partial::Google: '0'
  File::Spec: '0'
  Getopt::Long: '2.36'
  Import::Base: '0'
  List::Util: '1.29'
  Module::Runtime: '0'
  Moo::Lax: '0'
  Parse::RecDescent: '0'
  Path::Tiny: '0'
  Pod::Usage::Return: '0'
  Regexp::Common: '0'
  Text::Trim: '0'
  Type::Tiny: '0'
  Types::Standard: '0'
  YAML: '0'
  boolean: '0'
  perl: '5.010'
resources:
  IRC: irc://irc.perl.org/#yertl
  bugtracker: https://github.com/preaction/ETL-Yertl/issues
  homepage: https://github.com/preaction/ETL-Yertl
  repository: https://github.com/preaction/ETL-Yertl.git
version: '0.015'
x_authority: cpan:PREACTION
